spring:
  datasource:
    url: jdbc:h2:mem:testdb
    jdabhjdbhajdbas
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

